package com.example.mall.dao;

import com.example.mall.model.UmsAdminLoginLog;
import com.example.mall.model.UmsAdminLoginLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UmsAdminLoginLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_login_log
     *
     * @mbg.generated Sat Aug 12 16:18:25 CST 2023
     */
    long countByExample(UmsAdminLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_login_log
     *
     * @mbg.generated Sat Aug 12 16:18:25 CST 2023
     */
    int deleteByExample(UmsAdminLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_login_log
     *
     * @mbg.generated Sat Aug 12 16:18:25 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_login_log
     *
     * @mbg.generated Sat Aug 12 16:18:25 CST 2023
     */
    int insert(UmsAdminLoginLog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_login_log
     *
     * @mbg.generated Sat Aug 12 16:18:25 CST 2023
     */
    int insertSelective(UmsAdminLoginLog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_login_log
     *
     * @mbg.generated Sat Aug 12 16:18:25 CST 2023
     */
    List<UmsAdminLoginLog> selectByExample(UmsAdminLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_login_log
     *
     * @mbg.generated Sat Aug 12 16:18:25 CST 2023
     */
    UmsAdminLoginLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_login_log
     *
     * @mbg.generated Sat Aug 12 16:18:25 CST 2023
     */
    int updateByExampleSelective(@Param("row") UmsAdminLoginLog row, @Param("example") UmsAdminLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_login_log
     *
     * @mbg.generated Sat Aug 12 16:18:25 CST 2023
     */
    int updateByExample(@Param("row") UmsAdminLoginLog row, @Param("example") UmsAdminLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_login_log
     *
     * @mbg.generated Sat Aug 12 16:18:25 CST 2023
     */
    int updateByPrimaryKeySelective(UmsAdminLoginLog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_login_log
     *
     * @mbg.generated Sat Aug 12 16:18:25 CST 2023
     */
    int updateByPrimaryKey(UmsAdminLoginLog row);
}